### ISSUE TITLE
Google images support

### ISSUE THREAD

**Issue by javiavid** [cloudy9101/obsidian-image-inserter#1]
I like to use reference images in my notes and it would be very interesting if you could also support google images or other services.

Thanks for this plugin

**Comment by cloudy9101** [comment]
Sure, will consider supporting google images. Thanks, man.

**Comment by cloudy9101** [comment]
Given the integration effort and copyright issues, I assume this plugin will only support image sources that have an API and are free to use.
Until now, we support Pixabay and Pexels other than Unsplash and probably won't support Google images. So close this now.

**Comment by javiavid** [comment]
Ok, no problem
