### ISSUE TITLE
Enhancement request: Get Metadata/image from  Frontmatter

### ISSUE THREAD

**Issue by engage-results** [cloudy9101/obsidian-image-inserter#10]
I would like to have an additional option (configurable) to add more metadata to the frontmatter image, so that I can learn more about the image and access it on Unsplash for additional use.

I insert image to front matter almost daily. My use case is:

1. search a keyword that comes to mind for the day (yesterday "cute", last week one day it was "minions". another day it was "baby elephant") and place it in frontmatter.
2. sometimes i would like to use the image elsewhere, or download it in a different size to include elsewhere

Enhancement:

Two options:
1. add another metadata tag that either has the link to the image page (not the image) on unsplash so I can use that, also add a tag with the acknowledgement text that appears as the image caption when you paste in document so that I can access it that in frontmatter
2. add a command "insert image from frontmatter to document" or "insert image copy Unsplash page to clipboard" or "Insert image acknowledge frontmatter image"

Option 1 would just load the frontmatter up with some more helpful metadata that i can use to get at what I want.  I think the drawback of this is that the size of the frontmatter just grows, which I also can find distracting when there is a huge block of metadata before I even get to the document.

Option 2 (I don't know if this is possible but I think it should be) would be new plugin features that use the image URL in the Frontmatter to figure out the Unsplash page and from there return a URL of the page, or the acknowledgements (or both). One way to do this is to insert the frontmatter images (with the acknowledgement) at the current cursor position.  The other way could be to copy it to the clipboard so I can paste it somewhere.

For example this was the frontmatter image that I inserted into my daily note yesterday.

`banner: "https://images.unsplash.com/photo-1425082661705-1834bfd09dca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjAwOTd8MHwxfHNlYXJjaHwzfHxDdXRlfGVufDB8MHx8fDE2NzUxNTc2ODg&ixlib=rb-4.0.3&q=80&w=1080"`

This is the "Unsplash page" that I want to easily find with this enhancement request: 

`https://unsplash.com/photos/adK3Vu70DEQ`

and the acknowledgements/attribution:

`Photo by <a href="https://unsplash.com/@sweetmangostudios?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Ricky  Kharawala</a> on <a href="https://unsplash.com/images/feelings/cute?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">[Unsplash](https://unsplash.com/images/feelings/cute?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)</a>`

I use this plugin daily (at least). Thanks very much for providing it. Love the recent enhancements. This request would make your plugin that much more perfect for me. Thanks for considering.

**Comment by cloudy9101** [comment]
Hi @engage-results 

Great enhancement suggestion. I have a short consideration and want to make a basic design to make it more generic.

1. Add an option to allow users to insert the backlink (eg. photo URL on Unsplash, https://unsplash.com/photos/adK3Vu70DEQ) after the acknowledgments.
2. Add an option for the frontmatter insert. If this option is enabled, it will insert the acknowledgments and backlinks to the current cursor position when inserting the image into the frontmatter.

It will look like this. It will appear below the image inserted in the document or at the cursor position when insert into the frontmatter part.

> *[Backlink](https://unsplash.com/photos/adK3Vu70DEQ) | Photo by [Ricky Kharawala](https://unsplash.com/@sweetmangostudios?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com).*

How about this solution?

**Comment by engage-results** [comment]
I like that solution. Thanks!

**Comment by cloudy9101** [comment]
Please update the plugin to 0.3.2 and the plugin settings to switch on "insert backlink" and "append image referral at the end of the file".

**Comment by engage-results** [comment]
Thanks. It looks good and works well.

**Comment by cloudy9101** [comment]
You are welcome and thanks again for the feedback.
