### ISSUE TITLE
Integrating Pexels

### ISSUE THREAD

**Issue by Bluemoondragon07** [cloudy9101/obsidian-image-inserter#13]
Hi. I came across this website called Pexels, an image gallery similar to Unsplash and its free [api](https://www.pexels.com/api/). I skimmed through the documentation a bit and it seems to support the same search features as Unsplash's. I was wondering if you would be interested in integrating this api into the plug-in sometime in the future.

**Comment by cloudy9101** [comment]
Hi @Bluemoondragon07, thanks for a good idea. I just integrated Pexels in the new version https://github.com/cloudy9101/obsidian-image-inserter/releases/tag/0.5.1

**Comment by Bluemoondragon07** [comment]
Wow! I'm so excited to try this out! Thanks for creating and updating this plug-in!
