### ISSUE TITLE
insert with slash command

### ISSUE THREAD

**Issue by airtonix** [cloudy9101/obsidian-image-inserter#15]
how good would it be to able to just type `/unsplash` or `/pixabay` to insert an image.

I know right!!! awesome. ❤️

**Comment by airtonix** [comment]
oh seems like we only get `/image` 

![saitama-ok-face-bubble](https://user-images.githubusercontent.com/61225/225746398-db159b1b-3042-445e-aad9-4012b5dc1cae.png)

**Comment by airtonix** [comment]
nah the new utopia should allow us a shortcut to the provider. ⚒️

**Comment by cloudy9101** [comment]
From my point of view, Obsidian more rely on the command palette other than something like `/command`. It feels more like the way Notion has.
I'm kind of curious about what you want. Do you want to search images from different image sources directly? If so, we can find a way through the command palette.
