### ISSUE TITLE
Default image size

### ISSUE THREAD

**Issue by javiavid** [cloudy9101/obsidian-image-inserter#2]
When you insert an image it is usually too large in size and you have to reduce it manually.
Is there an option to define the default size in the plugin preferences?

**Comment by cloudy9101** [comment]
Thank you for the enhancement idea.
The feature added at 1c71eeec41b27af690d7820287bcce272e848d80

For now, I just added a setting for the default image size. In the future, I'd like to make it possible to modify when inserting.

**Comment by javiavid** [comment]
Thanks
