### ISSUE TITLE
Suggestion to change the wording in the new update; raw, high, medium, low

### ISSUE THREAD

**Issue by leafstrat** [cloudy9101/obsidian-image-inserter#20]
Unless I'm mistaken in what this feature is doing, these should be labelled as such;

- Raw
- Large
- Medium
- Small

From my looking at it, they are not really changing the quality of the image itself which would make sense for "High", "Medium", "Low" they are just adding URL arguments which change the display size. So I think my words make more sense in this case.

Love this new feature, it's superb!

**Comment by cloudy9101** [comment]
Right. That's misleading. Fixed in https://github.com/cloudy9101/obsidian-image-inserter/releases/tag/0.6.2
