### ISSUE TITLE
Multiple provider insert

### ISSUE THREAD

**Issue by TfTHacker** [cloudy9101/obsidian-image-inserter#23]
It would be interesting to have an option for inserting from any of the three providers. 

It could be that there are 3 separate commands, one for inserting by the provider or the modal could show previews from all enabled providers. Though the UI might be challenging to manage in this case. This makes me wonder if a side pane would be a better UI for searching for images and then inserting them into the current document and cursor location.

**Comment by cloudy9101** [comment]
Hi @TfTHacker, the provider selector in the modal, does that not meet your requirement? There's also a shortcut keybinding `ctrl - u` for switching providers.

<img width="580" alt="image" src="https://github.com/cloudy9101/obsidian-image-inserter/assets/5436425/b4a457e3-65b6-490d-a239-0479c405ea34">



But I'm pretty open to ideas, so just let me know your thought.

**Comment by TfTHacker** [comment]
Oh, I totally missed that in the UI 🤓. Very nice!

Just keep my "pane" idea in mind though, might be a more dynamic way of working with images for insertion.
