### ISSUE TITLE
BUG: image inserter inserts the image when i hover the image in the search results

### ISSUE THREAD

**Issue by materemias** [cloudy9101/obsidian-image-inserter#24]
strange thing, but recently the first image I hover automatically gets selected from the search results, it required (and should require) a click on picking the desired one

**Comment by cloudy9101** [comment]
Hi @materemias , thank you for reporting this issue.
However I can't reproduce it. Could you provide your Obsidian version, os version etc.?
And also if you can record a short video of the issue would be nice.

**Comment by materemias** [comment]
Hi @cloudy9101 ,

here is a quick video, I don't click the mouse just hover the image and it gets selected
https://github.com/cloudy9101/obsidian-image-inserter/assets/529994/6050db64-d6d3-48e5-b285-2f9bf72f00ed

I use Arch Linux (btw), and Obsidian v1.4.16, Image inserter v0.6.2.

let me know if you need any more specifics

**Comment by materemias** [comment]
I found that this only happens when [Image converter plugin](https://github.com/xryul/obsidian-image-converter) is also enabled, I am reporting this there too!
https://github.com/xRyul/obsidian-image-converter/issues/28

**Comment by materemias** [comment]
This was fixed
