### ISSUE TITLE
Insert backlink setting does not work

### ISSUE THREAD

**Issue by YongcaiHuang** [cloudy9101/obsidian-image-inserter#27]
when closing the `Insert backlink`, there is still `photo by XXXX on Unsplash` after image insertion.

**Comment by cloudy9101** [comment]
Hi @EricHUANG970823 
Thanks for reporting.
The `backlink` is the link of the website page of the image. `photo by XXX on Unsplash` is the referral that is required by Unsplash when using their images.
The `Insert backlink` control the insert of backlink. We don't have an option to control the referral but you can remove it after insert manually.
