### ISSUE TITLE
Local image option

### ISSUE THREAD

**Issue by javiavid** [cloudy9101/obsidian-image-inserter#3]
It would be interesting to have an option to choose if you want the images locally in the preferences.

Maybe something similar to what this plugin does would help:
https://github.com/niekcandaele/obsidian-local-images

**Comment by cloudy9101** [comment]
Actually, I thought about that when creating this plugin. I just got time today and added the feature. 2d2e339a37913314f888591d659e58e71b409eb9
Now there's an option in the settings tab and you can choose the insert mode which can be remote or locally.

Remote means the image will not be downloaded and just use the unsplash image URL.
Locally means the image will be downloaded in the attachment folder, then insert it into the note.

**Comment by javiavid** [comment]
Great!, thank you very much
