### ISSUE TITLE
More images

### ISSUE THREAD

**Issue by javiavid** [cloudy9101/obsidian-image-inserter#4]
Sometimes the image you are looking for is not in that selection of 9 images, I think it would be interesting to be able to choose between more images.

I have several ideas:
- Smaller thumbnails
- Bigger window
- Pagination, with some buttons and shortcuts to jump from page, for example, ctrl + right
- Scroll with the mouse

**Comment by cloudy9101** [comment]
You're right. But this needs to refactor the select image modal. I will work on this when I have time, maybe next week.

**Comment by cloudy9101** [comment]
Add pagination at https://github.com/cloudy9101/obsidian-image-inserter/releases/tag/0.1.3

To support pagination, we built a custom component to render the images list. It may have unknown bugs, but at least it works well when we test it.
And also increase the image number per page, now it will get 30 images once, that's the limit from Unsplash.

If there's any problem, please reopen this issue or create a new issue.

**Comment by javiavid** [comment]
Thanks for the update.
I've tried it but it doesn't work properly.

A window pops up, but I can't type in it.

![image](https://user-images.githubusercontent.com/7627504/195024672-14cd8d47-0410-4a7d-9f17-88dd50e1e339.png)

**Comment by cloudy9101** [comment]
Can you tell me your environment? Like the OS version and the Obsidian version.

**Comment by javiavid** [comment]
Windows 11 22h2

SYSTEM INFO:
	Obsidian version: v0.16.5
	Installer version: v0.15.9
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 7
	Plugins enabled: 4
		1: Dataview v0.5.47
		2: DB Folder v2.7.1
		3: Obsidian42 - BRAT v0.6.35
		4: Image Inserter v0.1.3

**Comment by cloudy9101** [comment]
@javiavid  It's a bug on windows. I fixed it at https://github.com/cloudy9101/obsidian-image-inserter/releases/tag/0.1.4, please have a try.

**Comment by javiavid** [comment]
The search and remote mode works!

Local mode does not work..

![image](https://user-images.githubusercontent.com/7627504/195075704-6aee8107-f257-432b-8063-071f0ee7108e.png)

**Comment by cloudy9101** [comment]
working on this

**Comment by cloudy9101** [comment]
@javiavid Sorry for the inconvenience, it should be fixed at https://github.com/cloudy9101/obsidian-image-inserter/releases/tag/0.1.5

**Comment by javiavid** [comment]
No problem, I appreciate your effort with the plugin.
Now it works correctly.
Thank you!
