### ISSUE TITLE
Results are not displayed

### ISSUE THREAD

**Issue by javiavid** [cloudy9101/obsidian-image-inserter#6]
I write text and the results do not appear, if I press enter an error appears.

https://user-images.githubusercontent.com/7627504/199930012-095504cd-db0e-4416-83ea-2d725cbbd119.mp4

SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v0.15.9
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 6
		1: Dataview v0.5.47
		2: DB Folder v2.8.1
		3: Obsidian42 - BRAT v0.6.36
		4: Image Inserter v0.1.5
		5: Projects v1.0.1
		6: Auto Link v1.0.6

**Comment by cloudy9101** [comment]
Something went wrong on the proxy server. Now fixed.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/5436425/200109866-d1f43f13-3780-4e34-8969-def188d8a6e6.png">
