### ISSUE TITLE
Banner / Projects compatibility - Frontmatter mode

### ISSUE THREAD

**Issue by javiavid** [cloudy9101/obsidian-image-inserter#8]
Both the Banner and Projects plugin use the frontmatter to select the image to display. It is also possible to use the same key and with a single line you can see the thumbnail in the Gallery view of Projects and as a Banner of the note.

It would be great if image inserter was also compatible with this system.
I propose:
- An option in preferences to select the frontmatter key, by default "image"
- A new command in the command palette, Insert Image to Frontmatter

Projects
https://github.com/marcusolsson/obsidian-projects
![image](https://user-images.githubusercontent.com/7627504/205608102-1790a597-4616-4582-952d-f1d096bd1582.png)

Banner
https://github.com/noatpad/obsidian-banners
![image](https://user-images.githubusercontent.com/7627504/205608182-576994dd-cd75-4e6b-a2bd-d803bfc509be.png)

**Comment by cloudy9101** [comment]
@javiavid 

Thank you for the idea.
Could you try https://github.com/cloudy9101/obsidian-image-inserter/releases/tag/0.1.8-pre and see if there's any issue or thought?
I also updated the README https://github.com/cloudy9101/obsidian-image-inserter/blob/frontmatter/README.md

**Comment by javiavid** [comment]
It works fine, although I found a bug.
If you have the key image_y: doesn't do it right and duplicates the image key.

Here are some examples:

GOOD
image: "https://images.unsplash.com/photo-1498887960847-2a5e46312788?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjAwOTd8MHwxfHNlYXJjaHwxM3x8Y2FyfGVufDB8MHx8fDE2NzA0NDI0ODI&ixlib=rb-4.0.3&q=80&w=1080"

WRONG
image: "https://images.unsplash.com/photo-1498887960847-2a5e46312788?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjAwOTd8MHwxfHNlYXJjaHwxM3x8Y2FyfGVufDB8MHx8fDE2NzA0NDI0ODI&ixlib=rb-4.0.3&q=80&w=1080"
image_y: 0.724

**Comment by cloudy9101** [comment]
Haha, I made a silly mistake. Will fix it later. Thanks for the test.

**Comment by javiavid** [comment]
Thanks

**Comment by cloudy9101** [comment]
Released in https://github.com/cloudy9101/obsidian-image-inserter/releases/tag/0.2.0. Please update the plugin.
